const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  const colors = [
    //Bleu
    { main: "Bleu", name: "Bleu", hue: "#0000FF" },
    { main: "Bleu", name: "Aigue-marine", hue: "#79F8F8" },
    { main: "Bleu", name: "Azur", hue: "#007FFF" },
    { main: "Bleu", name: "Azur", hue: "#1E7FCB" },
    { main: "Bleu", name: "Azur clair", hue: "#74D0F1" },
    { main: "Bleu", name: "Azurin", hue: "#A9EAFE" },
    { main: "Bleu", name: "Bleu acier", hue: "#3A8EBA" },
    { main: "Bleu", name: "Bleu ardoise", hue: "#686F8C" },
    { main: "Bleu", name: "Bleu barbeau", hue: "#5472AE" },
    { main: "Bleu", name: "Bleu bleuet", hue: "#5472AE" },
    { main: "Bleu", name: "Bleu bondi", hue: "#0095B6" },
    { main: "Bleu", name: "Bleu céleste", hue: "#26C4EC" },
    { main: "Bleu", name: "Bleu céruléen", hue: "#0F9DE8" },
    { main: "Bleu", name: "Bleu céruléen", hue: "#357AB7" },
    { main: "Bleu", name: "Bleu charrette", hue: "#8EA2C6" },
    { main: "Bleu", name: "Bleu charron", hue: "#17657D" },
    { main: "Bleu", name: "Bleu charron", hue: "#8EA2C6" },
    { main: "Bleu", name: "Bleu ciel", hue: "#77B5FE" },
    { main: "Bleu", name: "Bleu cobalt", hue: "#22427C" },
    { main: "Bleu", name: "Bleu de Berlin", hue: "#24445C" },
    { main: "Bleu", name: "Bleu de France", hue: "#318CE7" },
    { main: "Bleu", name: "Bleu de minuit", hue: "#003366" },
    { main: "Bleu", name: "Bleu de Prusse", hue: "#24445C" },
    { main: "Bleu", name: "Bleu denim", hue: "#1560BD" },
    { main: "Bleu", name: "Bleu des mers du sud", hue: "#00CCCB" },
    { main: "Bleu", name: "Bleu dragée", hue: "#DFF2FF" },
    { main: "Bleu", name: "Bleu égyptien", hue: "#1034A6" },
    { main: "Bleu", name: "Bleu électrique", hue: "#2C75FF" },
    { main: "Bleu", name: "Bleu guède", hue: "#56739A" },
    { main: "Bleu", name: "Bleu horizon", hue: "#7F8FA6" },
    { main: "Bleu", name: "Bleu majorelle", hue: "#6050DC" },
    { main: "Bleu", name: "Bleu marine", hue: "#03224C" },
    { main: "Bleu", name: "Bleu maya", hue: "#73C2FB" },
    { main: "Bleu", name: "Bleu minéral", hue: "#24445C" },
    { main: "Bleu", name: "Bleu nuit", hue: "#0F056B" },
    { main: "Bleu", name: "Bleu outremer", hue: "#1B019B" },
    { main: "Bleu", name: "Bleu outremer", hue: "#2B009A" },
    { main: "Bleu", name: "Bleu paon", hue: "#067790" },
    { main: "Bleu", name: "Bleu persan", hue: "#6600FF" },
    { main: "Bleu", name: "Bleu pétrole", hue: "#1D4851" },
    { main: "Bleu", name: "Bleu roi", hue: "#318CE7" },
    { main: "Bleu", name: "Bleu saphir", hue: "#0131B4" },
    { main: "Bleu", name: "Bleu sarcelle", hue: "#008080" },
    { main: "Bleu", name: "Bleu smalt", hue: "#003399" },
    { main: "Bleu", name: "Bleu tiffany", hue: "#0ABAB5" },
    { main: "Bleu", name: "Bleu turquin", hue: "#425B8A" },
    { main: "Bleu", name: "Cæruléum", hue: "#26C4EC" },
    { main: "Bleu", name: "Canard", hue: "#048B9A" },
    { main: "Bleu", name: "Cérulé", hue: "#74D0F1" },
    { main: "Bleu", name: "Cyan", hue: "#00FFFF" },
    { main: "Bleu", name: "Cyan", hue: "#2BFAFA" },
    { main: "Bleu", name: "Fumée", hue: "#BBD2E1" },
    { main: "Bleu", name: "Givré", hue: "#80D0D0" },
    { main: "Bleu", name: "Indigo", hue: "#791CF8" },
    { main: "Bleu", name: "Indigo", hue: "#2E006C" },
    { main: "Bleu", name: "Indigo du web", hue: "#4B0082" },
    { main: "Bleu", name: "Klein", hue: "#002FA7" },
    { main: "Bleu", name: "Klein", hue: "#21177D" },
    { main: "Bleu", name: "Lapis-lazuli", hue: "#26619C" },
    { main: "Bleu", name: "Lavande", hue: "#9683EC" },
    { main: "Bleu", name: "Pastel", hue: "#56739A" },
    { main: "Bleu", name: "Pervenche", hue: "#CCCCFF" },
    { main: "Bleu", name: "Turquoise", hue: "#25FDE9" },
    //Blanc
    { name: "Blanc", hue: "#FFFFFF", main: "Blanc" },
    { name: "Albâtre", hue: "#FEFEFE", main: "Blanc" },
    { name: "Argile", hue: "#EFEFEF", main: "Blanc" },
    { name: "Azur brume", hue: "#F0FFFF", main: "Blanc" },
    { name: "Beige clair", hue: "#F5F5DC", main: "Blanc" },
    { name: "Blanc cassé", hue: "#FEFEE2", main: "Blanc" },
    { name: "Blanc céruse", hue: "#FEFEFE", main: "Blanc" },
    { name: "Blanc crème", hue: "#FDF1B8", main: "Blanc" },
    { name: "Blanc d'argent", hue: "#FEFEFE", main: "Blanc" },
    { name: "Blanc de lait", hue: "#FBFCFA", main: "Blanc" },
    { name: "Blanc de lin", hue: "#FAF0E6", main: "Blanc" },
    { name: "Blanc de platine", hue: "#FAF0C5", main: "Blanc" },
    { name: "Blanc de plomb", hue: "#FEFEFE", main: "Blanc" },
    { name: "Blanc de Saturne", hue: "#FEFEFE", main: "Blanc" },
    { name: "Blanc de Troyes", hue: "#FEFDF0", main: "Blanc" },
    { name: "Blanc de Zinc", hue: "#F6FEFE", main: "Blanc" },
    { name: "Blanc d'Espagne", hue: "#FEFDF0", main: "Blanc" },
    { name: "Blanc d'ivoire", hue: "#FFFFF4", main: "Blanc" },
    { name: "Blanc écru", hue: "#FEFEE0", main: "Blanc" },
    { name: "Blanc lunaire", hue: "#F4FEFE", main: "Blanc" },
    { name: "Blanc neige", hue: "#FEFEFE", main: "Blanc" },
    { name: "Blanc opalin", hue: "#F2FFFF", main: "Blanc" },
    { name: "Blanc-bleu", hue: "#FEFEFE", main: "Blanc" },
    { name: "Coquille d'oeuf", hue: "#FDE9E0", main: "Blanc" },
    { name: "Cuisse de nymphe", hue: "#FEE7F0", main: "Blanc" },
    //Brun
    { name: "Brun", hue: "#5B3C11", main: "Brun" },
    { name: "Acajou", hue: "#88421D", main: "Brun" },
    { name: "Alezan", hue: "#A76726", main: "Brun" },
    { name: "Ambre", hue: "#F0C300", main: "Brun" },
    { name: "Auburn", hue: "#9D3E0C", main: "Brun" },
    { name: "Basané", hue: "#8B6C42", main: "Brun" },
    { name: "Beige", hue: "#C8AD7F", main: "Brun" },
    { name: "Beige clair", hue: "#F5F5DC", main: "Brun" },
    { name: "Beigeasse", hue: "#AFA778", main: "Brun" },
    { name: "Bistre", hue: "#3D2B1F", main: "Brun" },
    { name: "Bistre", hue: "#856D4D", main: "Brun" },
    { name: "Bitume", hue: "#4E3D28", main: "Brun" },
    { name: "Blet", hue: "#5B3C11", main: "Brun" },
    { name: "Brique", hue: "#842E1B", main: "Brun" },
    { name: "Bronze", hue: "#614E1A", main: "Brun" },
    { name: "Brou de noix", hue: "#3F2204", main: "Brun" },
    { name: "Bureau", hue: "#6B5731", main: "Brun" },
    { name: "Cacao", hue: "#614B3A", main: "Brun" },
    { name: "Cachou", hue: "#2F1B0C", main: "Brun" },
    { name: "Café", hue: "#462E01", main: "Brun" },
    { name: "Café au lait", hue: "#785E2F", main: "Brun" },
    { name: "Cannelle", hue: "#7E5835", main: "Brun" },
    { name: "Caramel", hue: "#7E3300", main: "Brun" },
    { name: "Châtaigne", hue: "#806D5A", main: "Brun" },
    { name: "Châtain", hue: "#8B6C42", main: "Brun" },
    { name: "Chaudron", hue: "#85530F", main: "Brun" },
    { name: "Chocolat", hue: "#5A3A22", main: "Brun" },
    { name: "Citrouille", hue: "#DF6D14", main: "Brun" },
    { name: "Fauve", hue: "#AD4F09", main: "Brun" },
    { name: "Feuille-morte", hue: "#99512B", main: "Brun" },
    { name: "Grège", hue: "#BBAE98", main: "Brun" },
    { name: "Gris de maure", hue: "#685E43", main: "Brun" },
    { name: "Lavallière", hue: "#8F5922", main: "Brun" },
    { name: "Marron", hue: "#582900", main: "Brun" },
    { name: "Mordoré", hue: "#87591A", main: "Brun" },
    { name: "Noisette", hue: "#955628", main: "Brun" },
    { name: "Orange brûlée", hue: "#CC5500", main: "Brun" },
    { name: "Puce", hue: "#4E1609", main: "Brun" },
    { name: "Rouge bismarck", hue: "#A5260A", main: "Brun" },
    { name: "Rouge tomette", hue: "#AE4A34", main: "Brun" },
    { name: "Rouille", hue: "#985717", main: "Brun" },
    { name: "Sang de boeuf", hue: "#730800", main: "Brun" },
    { name: "Senois", hue: "#8D4024", main: "Brun" },
    { name: "Sépia", hue: "#A98C78", main: "Brun" },
    { name: "Sépia", hue: "#AE8964", main: "Brun" },
    { name: "Tabac", hue: "#9F551E", main: "Brun" },
    { name: "Terre de Sienne", hue: "#8E5434", main: "Brun" },
    { name: "Terre d'ombre", hue: "#625B48", main: "Brun" },
    { name: "Terre d'ombre", hue: "#926D27", main: "Brun" },
    { name: "Vanille", hue: "#E1CE9A", main: "Brun" },
    //Gris
    { name: "Gris", hue: "#606060", main: "Gris" },
    { name: "Ardoise", hue: "#5A5E6B", main: "Gris" },
    { name: "Argent", hue: "#CECECE", main: "Gris" },
    { name: "Argile", hue: "#EFEFEF", main: "Gris" },
    { name: "Bis", hue: "#766F64", main: "Gris" },
    { name: "Bistre", hue: "#3D2B1F", main: "Gris" },
    { name: "Bistre", hue: "#856D4D", main: "Gris" },
    { name: "Bitume", hue: "#4E3D28", main: "Gris" },
    { name: "Céladon", hue: "#83A697", main: "Gris" },
    { name: "Châtaigne", hue: "#806D5A", main: "Gris" },
    { name: "Etain oxydé", hue: "#BABABA", main: "Gris" },
    { name: "Etain pur", hue: "#EDEDED", main: "Gris" },
    { name: "Fumée", hue: "#BBD2E1", main: "Gris" },
    { name: "Grège", hue: "#BBAE98", main: "Gris" },
    { name: "Gris acier", hue: "#AFAFAF", main: "Gris" },
    { name: "Gris anthracite", hue: "#303030", main: "Gris" },
    { name: "Gris de Payne", hue: "#677179", main: "Gris" },
    { name: "Gris fer", hue: "#848484", main: "Gris" },
    { name: "Gris Fer", hue: "#7F7F7F", main: "Gris" },
    { name: "Gris Perle", hue: "#CECECE", main: "Gris" },
    { name: "Gris Perle", hue: "#C7D0CC", main: "Gris" },
    { name: "Gris souris", hue: "#9E9E9E", main: "Gris" },
    { name: "Gris tourterelle", hue: "#BBACAC", main: "Gris" },
    { name: "Mastic", hue: "#B3B191", main: "Gris" },
    { name: "Pinchard", hue: "#CCCCCC", main: "Gris" },
    { name: "Plomb", hue: "#798081", main: "Gris" },
    { name: "Rose Mountbatten", hue: "#997A8D", main: "Gris" },
    { name: "Taupe", hue: "#463F32", main: "Gris" },
    { name: "Tourdille", hue: "#C1BFB1", main: "Gris" },
    //Jaune
    { name: "Jaune", hue: "#FFFF00", main: "Jaune" },
    { name: "Ambre", hue: "#F0C300", main: "Jaune" },
    { name: "Aurore", hue: "#FFCB60", main: "Jaune" },
    { name: "Beurre", hue: "#F0E36B", main: "Jaune" },
    { name: "Beurre frais", hue: "#FFF48D", main: "Jaune" },
    { name: "Blé", hue: "#E8D630", main: "Jaune" },
    { name: "Blond", hue: "#E2BC74", main: "Jaune" },
    { name: "Boutton d'or", hue: "#FCDC12", main: "Jaune" },
    { name: "Bulle", hue: "#EDD38C", main: "Jaune" },
    { name: "Caca d'oie", hue: "#CDCD0D", main: "Jaune" },
    { name: "Chamois", hue: "#D0C07A", main: "Jaune" },
    { name: "Champagne", hue: "#FBF2B7", main: "Jaune" },
    { name: "Chrome", hue: "#EDFF0C", main: "Jaune" },
    { name: "Chrome", hue: "#FFFF05", main: "Jaune" },
    { name: "Citron", hue: "#F7FF3C", main: "Jaune" },
    { name: "Fauve", hue: "#AD4F09", main: "Jaune" },
    { name: "Flave", hue: "#E6E697", main: "Jaune" },
    { name: "Fleur de soufre", hue: "#FFFF6B", main: "Jaune" },
    { name: "Gomme-gutte", hue: "#EF9B0F", main: "Jaune" },
    { name: "Jaune auréolin", hue: "#EFD242", main: "Jaune" },
    { name: "Jaune banane", hue: "#D1B606", main: "Jaune" },
    { name: "Jaune canari", hue: "#E7F00D", main: "Jaune" },
    { name: "Jaune chartreuse", hue: "#DFFF00", main: "Jaune" },
    { name: "Jaune de cobalt", hue: "#FDEE00", main: "Jaune" },
    { name: "Jaune de Naples", hue: "#FFF0BC", main: "Jaune" },
    { name: "Jaune d'or", hue: "#EFD807", main: "Jaune" },
    { name: "Jaune impérial", hue: "#FFE436", main: "Jaune" },
    { name: "Jaune mimosa", hue: "#FEF86C", main: "Jaune" },
    { name: "Jaune moutarde", hue: "#C7CF00", main: "Jaune" },
    { name: "Jaune nankin", hue: "#F7E269", main: "Jaune" },
    { name: "Jaune olive", hue: "#808000", main: "Jaune" },
    { name: "Jaune paille", hue: "#FEE347", main: "Jaune" },
    { name: "Jaune poussin", hue: "#F7E35F", main: "Jaune" },
    { name: "Maïs", hue: "#FFDE75", main: "Jaune" },
    { name: "Mars", hue: "#EED153", main: "Jaune" },
    { name: "Mastic", hue: "#B3B191", main: "Jaune" },
    { name: "Miel", hue: "#DAB30A", main: "Jaune" },
    { name: "Ocre jaune", hue: "#DFAF2C", main: "Jaune" },
    { name: "Ocre rouge", hue: "#DD985C", main: "Jaune" },
    { name: "Or", hue: "#FFD700", main: "Jaune" },
    { name: "Orpiment", hue: "#FCD21C", main: "Jaune" },
    { name: "Poil de chameau", hue: "#B67823", main: "Jaune" },
    { name: "Queue de vache", hue: "#C3B470", main: "Jaune" },
    { name: "Queue de vache", hue: "#A89874", main: "Jaune" },
    { name: "Sable", hue: "#E0CDA9", main: "Jaune" },
    { name: "Safran", hue: "#F4C430", main: "Jaune" },
    { name: "Soufre", hue: "#FFFF6B", main: "Jaune" },
    { name: "Topaze", hue: "#FAEA73", main: "Jaune" },
    { name: "Vanille", hue: "#E1CE9A", main: "Jaune" },
    { name: "Vénitien", hue: "#E7A854", main: "Jaune" },
    //Noir
    // { name: "Noir", hue: "#000000", main: "Noir" },
    // { name: "Aile de corbeau", hue: "#000000", main: "Noir" },
    // { name: "Brou de noix", hue: "#3F2204", main: "Noir" },
    // { name: "Cassis", hue: "#2C030B", main: "Noir" },
    // { name: "Cassis", hue: "#3A020D", main: "Noir" },
    // { name: "Dorian", hue: "#0B1616", main: "Noir" },
    // { name: "Ebène", hue: "#000000", main: "Noir" },
    // { name: "Noir animal", hue: "#000000", main: "Noir" },
    // { name: "Noir charbon", hue: "#000000", main: "Noir" },
    // { name: "Noir d'aniline", hue: "#120D16", main: "Noir" },
    // { name: "Noir de carbone", hue: "#130E0A", main: "Noir" },
    // { name: "Noir de fumée", hue: "#130E0A", main: "Noir" },
    // { name: "Noir de jais", hue: "#000000", main: "Noir" },
    // { name: "Noir d'encre", hue: "#000000", main: "Noir" },
    // { name: "Noir d'ivoire", hue: "#000000", main: "Noir" },
    // { name: "Noiraud", hue: "#2F1E0E", main: "Noir" },
    // { name: "Réglisse", hue: "#2D241E", main: "Noir" },
    //Orange
    { name: "Orange", hue: "#ED7F10", main: "Orange" },
    { name: "Abricot", hue: "#E67E30", main: "Orange" },
    { name: "Aurore", hue: "#FFCB60", main: "Orange" },
    { name: "Bis", hue: "#F1E2BE", main: "Orange" },
    { name: "Bisque", hue: "#FFE4C4", main: "Orange" },
    { name: "Carotte", hue: "#F4661B", main: "Orange" },
    { name: "Citrouille", hue: "#DF6D14", main: "Orange" },
    { name: "Corail", hue: "#E73E01", main: "Orange" },
    { name: "Cuivre", hue: "#B36700", main: "Orange" },
    { name: "Gomme-gutte", hue: "#EF9B0F", main: "Orange" },
    { name: "Mandarine", hue: "#FEA347", main: "Orange" },
    { name: "Melon", hue: "#DE9816", main: "Orange" },
    { name: "Orangé", hue: "#FAA401", main: "Orange" },
    { name: "Orange brûlée", hue: "#CC5500", main: "Orange" },
    { name: "Roux", hue: "#AD4F09", main: "Orange" },
    { name: "Safran", hue: "#F3D617", main: "Orange" },
    { name: "Saumon", hue: "#F88E55", main: "Orange" },
    { name: "Tangerine", hue: "#FF7F00", main: "Orange" },
    { name: "Tanné", hue: "#A75502", main: "Orange" },
    { name: "Vanille", hue: "#E1CE9A", main: "Orange" },
    { name: "Ventre de biche", hue: "#E9C9B1", main: "Orange" },
    // Rose
    { name: "Rose", hue: "#FD6C9E", main: "Rose" },
    { name: "Bisque", hue: "#FFE4C4", main: "Rose" },
    { name: "Cerise", hue: "#DE3163", main: "Rose" },
    { name: "Chair", hue: "#FEC3AC", main: "Rose" },
    { name: "Coquille d'oeuf", hue: "#FDE9E0", main: "Rose" },
    { name: "Cuisse de nymphe", hue: "#FEE7F0", main: "Rose" },
    { name: "Framboise", hue: "#C72C48", main: "Rose" },
    { name: "Fushia", hue: "#FD3F92", main: "Rose" },
    { name: "Héliotrope", hue: "#DF73FF", main: "Rose" },
    { name: "Incarnadin", hue: "#FE96A0", main: "Rose" },
    { name: "Magenta", hue: "#FF00FF", main: "Rose" },
    { name: "Magenta foncé", hue: "#800080", main: "Rose" },
    { name: "Magenta fushia", hue: "#DB0073", main: "Rose" },
    { name: "Mauve", hue: "#D473D4", main: "Rose" },
    { name: "Pêche", hue: "#FDBFB7", main: "Rose" },
    { name: "Rose balais", hue: "#C4698F", main: "Rose" },
    { name: "Rose bonbon", hue: "#F9429E", main: "Rose" },
    { name: "Rose dragée", hue: "#FEBFD2", main: "Rose" },
    { name: "Rose Mountbatten", hue: "#997A8D", main: "Rose" },
    { name: "Rose thé", hue: "#FF866A", main: "Rose" },
    { name: "Rose vif", hue: "#FF007F", main: "Rose" },
    { name: "Saumon", hue: "#F88E55", main: "Rose" },
    //Rouge
    { name: "Rouge", hue: "#FF0000", main: "Rouge" },
    { name: "Amarante", hue: "#91283B", main: "Rouge" },
    { name: "Bordeaux", hue: "#6D071A", main: "Rouge" },
    { name: "Brique", hue: "#842E1B", main: "Rouge" },
    { name: "Cerise", hue: "#BB0B0B", main: "Rouge" },
    { name: "Corail", hue: "#E73E01", main: "Rouge" },
    { name: "Ecarlate", hue: "#ED0000", main: "Rouge" },
    { name: "Fraise", hue: "#BF3030", main: "Rouge" },
    { name: "Fraise écrasée", hue: "#A42424", main: "Rouge" },
    { name: "Framboise", hue: "#C72C48", main: "Rouge" },
    { name: "Fushia", hue: "#FD3F92", main: "Rouge" },
    { name: "Grenadine", hue: "#E9383F", main: "Rouge" },
    { name: "Grenat", hue: "#6E0B14", main: "Rouge" },
    { name: "Incarnadin", hue: "#FE96A0", main: "Rouge" },
    { name: "Incarnat", hue: "#FF6F7D", main: "Rouge" },
    { name: "Magenta", hue: "#FF00FF", main: "Rouge" },
    { name: "Magenta foncé", hue: "#800080", main: "Rouge" },
    { name: "Magenta fushia", hue: "#DB0073", main: "Rouge" },
    { name: "Mauve", hue: "#D473D4", main: "Rouge" },
    { name: "Nacarat", hue: "#FC5D5D", main: "Rouge" },
    { name: "Ocre rouge", hue: "#DD985C", main: "Rouge" },
    { name: "Passe-velours", hue: "#91283B", main: "Rouge" },
    { name: "Pourpre", hue: "#9E0E40", main: "Rouge" },
    { name: "Prune", hue: "#811453", main: "Rouge" },
    { name: "Rose vif", hue: "#FF007F", main: "Rouge" },
    { name: "Rouge alizarine", hue: "#D90115", main: "Rouge" },
    { name: "Rouge anglais", hue: "#F7230C", main: "Rouge" },
    { name: "Rouge bismarck", hue: "#A5260A", main: "Rouge" },
    { name: "Rouge bourgogne", hue: "#6B0D0D", main: "Rouge" },
    { name: "Rouge capucine", hue: "#FF5E4D", main: "Rouge" },
    { name: "Rouge cardinal", hue: "#B82010", main: "Rouge" },
    { name: "Rouge carmin", hue: "#960018", main: "Rouge" },
    { name: "Rouge cinabre", hue: "#DB1702", main: "Rouge" },
    { name: "Rouge coquelicot", hue: "#C60800", main: "Rouge" },
    { name: "Rouge cramoisi", hue: "#960018", main: "Rouge" },
    { name: "Rouge d'Andrinople", hue: "#A91101", main: "Rouge" },
    { name: "Rouge d'aniline", hue: "#EB0000", main: "Rouge" },
    { name: "Rouge de falun", hue: "#801818", main: "Rouge" },
    { name: "Rouge de mars", hue: "#F7230C", main: "Rouge" },
    { name: "Rouge écrevisse", hue: "#BC2001", main: "Rouge" },
    { name: "Rouge feu", hue: "#FE1B00", main: "Rouge" },
    { name: "Rouge garance", hue: "#EE1010", main: "Rouge" },
    { name: "Rouge groseille", hue: "#CF0A1D", main: "Rouge" },
    { name: "Rouge ponceau", hue: "#C60800", main: "Rouge" },
    { name: "Rouge rubis", hue: "#E0115F", main: "Rouge" },
    { name: "Rouge sang", hue: "#850606", main: "Rouge" },
    { name: "Rouge tomate", hue: "#DE2916", main: "Rouge" },
    { name: "Rouge tomette", hue: "#AE4A34", main: "Rouge" },
    { name: "Rouge turc", hue: "#A91101", main: "Rouge" },
    { name: "Rouge vermillon", hue: "#DB1702", main: "Rouge" },
    { name: "Rouge-violet", hue: "#C71585", main: "Rouge" },
    { name: "Rouille", hue: "#985717", main: "Rouge" },
    { name: "Sang de boeuf", hue: "#730800", main: "Rouge" },
    { name: "Senois", hue: "#8D4024", main: "Rouge" },
    { name: "Terracotta", hue: "#CC4E5C", main: "Rouge" },
    { name: "Vermeil", hue: "#FF0921", main: "Rouge" },
    { name: "Zizolin", hue: "#6C0277", main: "Rouge" },
    //Vert
    { name: "Vert", hue: "#00FF00", main: "Vert" },
    { name: "Aigue-marine", hue: "#79F8F8", main: "Vert" },
    { name: "Asperge", hue: "#7BA05B", main: "Vert" },
    { name: "Bleu sarcelle", hue: "#008E8E", main: "Vert" },
    { name: "Canard", hue: "#048B9A", main: "Vert" },
    { name: "Céladon", hue: "#83A697", main: "Vert" },
    { name: "Givré", hue: "#80D0D0", main: "Vert" },
    { name: "Glauque", hue: "#649B88", main: "Vert" },
    { name: "Hooker", hue: "#1B4F08", main: "Vert" },
    { name: "Jade", hue: "#87E990", main: "Vert" },
    { name: "Kaki", hue: "#94812B", main: "Vert" },
    { name: "Menthe", hue: "#16B84E", main: "Vert" },
    { name: "Menthe à l'eau", hue: "#54F98D", main: "Vert" },
    { name: "Sinople", hue: "#149414", main: "Vert" },
    { name: "Turquoise", hue: "#25FDE9", main: "Vert" },
    { name: "Vert absinthe", hue: "#7FDD4C", main: "Vert" },
    { name: "Vert amande", hue: "#82C46C", main: "Vert" },
    { name: "Vert anglais", hue: "#18391E", main: "Vert" },
    { name: "Vert anis", hue: "#9FE855", main: "Vert" },
    { name: "Vert avocat", hue: "#568203", main: "Vert" },
    { name: "Vert bouteille", hue: "#096A09", main: "Vert" },
    { name: "Vert chartreuse", hue: "#C2F732", main: "Vert" },
    { name: "Vert citron", hue: "#00FF00", main: "Vert" },
    { name: "Vert de chrome", hue: "#18391E", main: "Vert" },
    { name: "Vert de gris", hue: "#95A595", main: "Vert" },
    { name: "Vert de vessie", hue: "#22780F", main: "Vert" },
    { name: "Vert d'eau", hue: "#B0F2B6", main: "Vert" },
    { name: "Vert émeraude", hue: "#01D758", main: "Vert" },
    { name: "Vert empire", hue: "#00561B", main: "Vert" },
    { name: "Vert épinard", hue: "#175732", main: "Vert" },
    { name: "Vert gazon", hue: "#3A9D23", main: "Vert" },
    { name: "Vert impérial", hue: "#00561B", main: "Vert" },
    { name: "Vert kaki", hue: "#798933", main: "Vert" },
    { name: "Vert lichen", hue: "#85C17E", main: "Vert" },
    { name: "Vert lime", hue: "#9EFD38", main: "Vert" },
    { name: "Vert malachite", hue: "#1FA055", main: "Vert" },
    { name: "Vert mélèse", hue: "#386F48", main: "Vert" },
    { name: "Vert militaire", hue: "#596643", main: "Vert" },
    { name: "Vert mousse", hue: "#679F5A", main: "Vert" },
    { name: "Vert olive", hue: "#708D23", main: "Vert" },
    { name: "Vert opaline", hue: "#97DFC6", main: "Vert" },
    { name: "Vert perroquet", hue: "#3AF24B", main: "Vert" },
    { name: "Vert pin", hue: "#01796F", main: "Vert" },
    { name: "Vert pistache", hue: "#BEF574", main: "Vert" },
    { name: "Vert poireau", hue: "#4CA66B", main: "Vert" },
    { name: "Vert pomme", hue: "#34C924", main: "Vert" },
    { name: "Vert prairie", hue: "#57D53B", main: "Vert" },
    { name: "Vert prasin", hue: "#4CA66B", main: "Vert" },
    { name: "Vert printemps", hue: "#00FE7E", main: "Vert" },
    { name: "Vert sapin", hue: "#095228", main: "Vert" },
    { name: "Vert sauge", hue: "#689D71", main: "Vert" },
    { name: "Vert smaragdin", hue: "#01D758", main: "Vert" },
    { name: "Vert tilleul", hue: "#A5D152", main: "Vert" },
    { name: "Vert véronèse", hue: "#586F2D", main: "Vert" },
    { name: "Vert viride", hue: "#40826D", main: "Vert" },
    //Violet
    { name: "Violet", hue: "#660099", main: "Violet" },
    { name: "Améthyste", hue: "#884DA7", main: "Violet" },
    { name: "Aubergine", hue: "#370028", main: "Violet" },
    { name: "Bleu persan", hue: "#6600FF", main: "Violet" },
    { name: "Byzantin", hue: "#BD33A4", main: "Violet" },
    { name: "Byzantium", hue: "#702963", main: "Violet" },
    { name: "Cerise", hue: "#DE3163", main: "Violet" },
    { name: "Colombin", hue: "#6A455D", main: "Violet" },
    { name: "Fushia", hue: "#FD3F92", main: "Violet" },
    { name: "Glycine", hue: "#C9A0DC", main: "Violet" },
    { name: "Gris de lin", hue: "#D2CAEC", main: "Violet" },
    { name: "Héliotrope", hue: "#DF73FF", main: "Violet" },
    { name: "Indigo", hue: "#791CF8", main: "Violet" },
    { name: "Indigo du web", hue: "#4B0082", main: "Violet" },
    { name: "Lavande", hue: "#9683EC", main: "Violet" },
    { name: "Lie de vin", hue: "#AC1E44", main: "Violet" },
    { name: "Lilas", hue: "#B666D2", main: "Violet" },
    { name: "Magenta", hue: "#FF00FF", main: "Violet" },
    { name: "Magenta foncé", hue: "#800080", main: "Violet" },
    { name: "Magenta fushia", hue: "#DB0073", main: "Violet" },
    { name: "Mauve", hue: "#D473D4", main: "Violet" },
    { name: "Orchidée", hue: "#DA70D6", main: "Violet" },
    { name: "Parme", hue: "#CFA0E9", main: "Violet" },
    { name: "Pourpre", hue: "#9E0E40", main: "Violet" },
    { name: "Prune", hue: "#811453", main: "Violet" },
    { name: "Rose bonbon", hue: "#F9429E", main: "Violet" },
    { name: "Rose vif", hue: "#FF007F", main: "Violet" },
    { name: "Rouge-violet", hue: "#C71585", main: "Violet" },
    { name: "Violet d'évêque", hue: "#723E64", main: "Violet" },
    { name: "Violine", hue: "#A10684", main: "Violet" },
    { name: "Zizolin", hue: "#6C0277", main: "Violet" },
  ];

  for (const color of colors) {
    await prisma.color.create({
      data: color,
    });
  }

  console.log("Database seeded successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
